/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilleRouteImport } from './routes/famille'
import { Route as EnfantsRouteImport } from './routes/enfants'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaiementSuccesRouteImport } from './routes/paiement.succes'
import { Route as PaiementEchecRouteImport } from './routes/paiement.echec'
import { Route as AideMentionsLegalesRouteImport } from './routes/aide.mentions-legales'
import { Route as AideLivraisonRouteImport } from './routes/aide.livraison'
import { Route as AideGuideTaillesRouteImport } from './routes/aide.guide-tailles'
import { Route as AideContactRouteImport } from './routes/aide.contact'
import { Route as AideConfidentialiteRouteImport } from './routes/aide.confidentialite'
import { Route as AideCgvRouteImport } from './routes/aide.cgv'
import { Route as AideCguRouteImport } from './routes/aide.cgu'
import { Route as EnfantsChildIdHistoriqueRouteImport } from './routes/enfants.$childId.historique'
import { Route as ApiPublicPayplugWebhookRouteImport } from './routes/api/public/payplug.webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilleRoute = FamilleRouteImport.update({
  id: '/famille',
  path: '/famille',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsRoute = EnfantsRouteImport.update({
  id: '/enfants',
  path: '/enfants',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementSuccesRoute = PaiementSuccesRouteImport.update({
  id: '/paiement/succes',
  path: '/paiement/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementEchecRoute = PaiementEchecRouteImport.update({
  id: '/paiement/echec',
  path: '/paiement/echec',
  getParentRoute: () => rootRouteImport,
} as any)
const AideMentionsLegalesRoute = AideMentionsLegalesRouteImport.update({
  id: '/aide/mentions-legales',
  path: '/aide/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const AideLivraisonRoute = AideLivraisonRouteImport.update({
  id: '/aide/livraison',
  path: '/aide/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const AideGuideTaillesRoute = AideGuideTaillesRouteImport.update({
  id: '/aide/guide-tailles',
  path: '/aide/guide-tailles',
  getParentRoute: () => rootRouteImport,
} as any)
const AideContactRoute = AideContactRouteImport.update({
  id: '/aide/contact',
  path: '/aide/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AideConfidentialiteRoute = AideConfidentialiteRouteImport.update({
  id: '/aide/confidentialite',
  path: '/aide/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AideCgvRoute = AideCgvRouteImport.update({
  id: '/aide/cgv',
  path: '/aide/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AideCguRoute = AideCguRouteImport.update({
  id: '/aide/cgu',
  path: '/aide/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsChildIdHistoriqueRoute =
  EnfantsChildIdHistoriqueRouteImport.update({
    id: '/$childId/historique',
    path: '/$childId/historique',
    getParentRoute: () => EnfantsRoute,
  } as any)
const ApiPublicPayplugWebhookRoute = ApiPublicPayplugWebhookRouteImport.update({
  id: '/api/public/payplug/webhook',
  path: '/api/public/payplug/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/commandes': typeof CommandesRoute
  '/enfants': typeof EnfantsRouteWithChildren
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/cgv': typeof AideCgvRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
  '/paiement/echec': typeof PaiementEchecRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/enfants/$childId/historique': typeof EnfantsChildIdHistoriqueRoute
  '/api/public/payplug/webhook': typeof ApiPublicPayplugWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/commandes': typeof CommandesRoute
  '/enfants': typeof EnfantsRouteWithChildren
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/cgv': typeof AideCgvRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
  '/paiement/echec': typeof PaiementEchecRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/enfants/$childId/historique': typeof EnfantsChildIdHistoriqueRoute
  '/api/public/payplug/webhook': typeof ApiPublicPayplugWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/commandes': typeof CommandesRoute
  '/enfants': typeof EnfantsRouteWithChildren
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/cgv': typeof AideCgvRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
  '/paiement/echec': typeof PaiementEchecRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/enfants/$childId/historique': typeof EnfantsChildIdHistoriqueRoute
  '/api/public/payplug/webhook': typeof ApiPublicPayplugWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boutique'
    | '/commandes'
    | '/enfants'
    | '/famille'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/aide/cgu'
    | '/aide/cgv'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
    | '/paiement/echec'
    | '/paiement/succes'
    | '/enfants/$childId/historique'
    | '/api/public/payplug/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/boutique'
    | '/commandes'
    | '/enfants'
    | '/famille'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/aide/cgu'
    | '/aide/cgv'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
    | '/paiement/echec'
    | '/paiement/succes'
    | '/enfants/$childId/historique'
    | '/api/public/payplug/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boutique'
    | '/commandes'
    | '/enfants'
    | '/famille'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/aide/cgu'
    | '/aide/cgv'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
    | '/paiement/echec'
    | '/paiement/succes'
    | '/enfants/$childId/historique'
    | '/api/public/payplug/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CommandesRoute: typeof CommandesRoute
  EnfantsRoute: typeof EnfantsRouteWithChildren
  FamilleRoute: typeof FamilleRoute
  LoginRoute: typeof LoginRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  PanierRoute: typeof PanierRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AideCguRoute: typeof AideCguRoute
  AideCgvRoute: typeof AideCgvRoute
  AideConfidentialiteRoute: typeof AideConfidentialiteRoute
  AideContactRoute: typeof AideContactRoute
  AideGuideTaillesRoute: typeof AideGuideTaillesRoute
  AideLivraisonRoute: typeof AideLivraisonRoute
  AideMentionsLegalesRoute: typeof AideMentionsLegalesRoute
  PaiementEchecRoute: typeof PaiementEchecRoute
  PaiementSuccesRoute: typeof PaiementSuccesRoute
  ApiPublicPayplugWebhookRoute: typeof ApiPublicPayplugWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/famille': {
      id: '/famille'
      path: '/famille'
      fullPath: '/famille'
      preLoaderRoute: typeof FamilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants': {
      id: '/enfants'
      path: '/enfants'
      fullPath: '/enfants'
      preLoaderRoute: typeof EnfantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/succes': {
      id: '/paiement/succes'
      path: '/paiement/succes'
      fullPath: '/paiement/succes'
      preLoaderRoute: typeof PaiementSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/echec': {
      id: '/paiement/echec'
      path: '/paiement/echec'
      fullPath: '/paiement/echec'
      preLoaderRoute: typeof PaiementEchecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/mentions-legales': {
      id: '/aide/mentions-legales'
      path: '/aide/mentions-legales'
      fullPath: '/aide/mentions-legales'
      preLoaderRoute: typeof AideMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/livraison': {
      id: '/aide/livraison'
      path: '/aide/livraison'
      fullPath: '/aide/livraison'
      preLoaderRoute: typeof AideLivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/guide-tailles': {
      id: '/aide/guide-tailles'
      path: '/aide/guide-tailles'
      fullPath: '/aide/guide-tailles'
      preLoaderRoute: typeof AideGuideTaillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/contact': {
      id: '/aide/contact'
      path: '/aide/contact'
      fullPath: '/aide/contact'
      preLoaderRoute: typeof AideContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/confidentialite': {
      id: '/aide/confidentialite'
      path: '/aide/confidentialite'
      fullPath: '/aide/confidentialite'
      preLoaderRoute: typeof AideConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/cgv': {
      id: '/aide/cgv'
      path: '/aide/cgv'
      fullPath: '/aide/cgv'
      preLoaderRoute: typeof AideCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/cgu': {
      id: '/aide/cgu'
      path: '/aide/cgu'
      fullPath: '/aide/cgu'
      preLoaderRoute: typeof AideCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants/$childId/historique': {
      id: '/enfants/$childId/historique'
      path: '/$childId/historique'
      fullPath: '/enfants/$childId/historique'
      preLoaderRoute: typeof EnfantsChildIdHistoriqueRouteImport
      parentRoute: typeof EnfantsRoute
    }
    '/api/public/payplug/webhook': {
      id: '/api/public/payplug/webhook'
      path: '/api/public/payplug/webhook'
      fullPath: '/api/public/payplug/webhook'
      preLoaderRoute: typeof ApiPublicPayplugWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnfantsRouteChildren {
  EnfantsChildIdHistoriqueRoute: typeof EnfantsChildIdHistoriqueRoute
}

const EnfantsRouteChildren: EnfantsRouteChildren = {
  EnfantsChildIdHistoriqueRoute: EnfantsChildIdHistoriqueRoute,
}

const EnfantsRouteWithChildren =
  EnfantsRoute._addFileChildren(EnfantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BoutiqueRoute: BoutiqueRoute,
  CommandesRoute: CommandesRoute,
  EnfantsRoute: EnfantsRouteWithChildren,
  FamilleRoute: FamilleRoute,
  LoginRoute: LoginRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  PanierRoute: PanierRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AideCguRoute: AideCguRoute,
  AideCgvRoute: AideCgvRoute,
  AideConfidentialiteRoute: AideConfidentialiteRoute,
  AideContactRoute: AideContactRoute,
  AideGuideTaillesRoute: AideGuideTaillesRoute,
  AideLivraisonRoute: AideLivraisonRoute,
  AideMentionsLegalesRoute: AideMentionsLegalesRoute,
  PaiementEchecRoute: PaiementEchecRoute,
  PaiementSuccesRoute: PaiementSuccesRoute,
  ApiPublicPayplugWebhookRoute: ApiPublicPayplugWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
