/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnfantsRouteImport } from './routes/enfants'
import { Route as IndexRouteImport } from './routes/index'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsRoute = EnfantsRouteImport.update({
  id: '/enfants',
  path: '/enfants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/enfants' | '/login' | '/panier'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/enfants' | '/login' | '/panier'
  id: '__root__' | '/' | '/enfants' | '/login' | '/panier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnfantsRoute: typeof EnfantsRoute
  LoginRoute: typeof LoginRoute
  PanierRoute: typeof PanierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants': {
      id: '/enfants'
      path: '/enfants'
      fullPath: '/enfants'
      preLoaderRoute: typeof EnfantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnfantsRoute: EnfantsRoute,
  LoginRoute: LoginRoute,
  PanierRoute: PanierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
